runtime: nodejs16
instance_class: F2

env_variables:
  NODE_ENV: 'production'
  PORT: 8080

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5 